name: frontend

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::465068362057:role/udemy-github-actions-frontend-deployment-role
          aws-region: ap-northeast-1
      - run: aws s3 sync . s3://udemy-github-actions-fj23-hkk-s3 --exact-timestamps --region ap-northeast-1
